# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Quantum Robotic Chivalry
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We develop games, development tools and other things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://qrclabs.moe" # the base hostname & protocol for your site
twitter_username: QRCLabs
#github_username:

# Build settings
markdown: kramdown
